(function compositionLibrary(){
'use strict';

const LOCAL_KEY='yd-showcase-compositions-v1';
const FOLDER_KEY='yd-showcase-folders-v1';
const MIGRATION_KEY='yd-showcase-layout-draft-v2:only';
const DRAFT_KEY='yd-showcase-layout-draft-v2';
const ORDER_KEY='yd-showcase-layout-order-v1';
const TEMPLATE_LABELS={
  'phone-long':'手机长图','ppt-flow':'PPT 智能四格图文流','a4-flow':'A4 智能图文流','ppt-3-text':'PPT 三图＋文字','ppt-flex':'PPT 自定义分页',
  'desktop-4-landscape':'电脑横版 4 图','desktop-4-portrait':'电脑竖版 4 图',
  'desktop-6-landscape':'电脑横版 6 图','desktop-6-portrait':'电脑竖版 6 图',
  'desktop-9-landscape':'电脑横版 9 图','desktop-9-portrait':'电脑竖版 9 图',
};
const ui={trash:false,saveAs:false,selectedFolder:'all',library:{folders:[],compositions:[]},libraryQuery:'',researchDetail:null,researchItem:null,researchFilter:'all',livePreviewCharts:new Map(),previewRun:0,accessItem:null,accessMode:'toggle'};
const byId=id=>document.getElementById(id);
const composer=()=>window.ShowcaseComposer;
const localMode=()=>typeof STATIC_MODE!=='undefined'&&STATIC_MODE;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeJSON=(value,fallback)=>{try{return JSON.parse(value)}catch{return fallback}};
const clone=value=>JSON.parse(JSON.stringify(value));
const now=()=>new Date().toISOString();
function compositionExternalLinks(source={}){const raw=Array.isArray(source?.external_links)?source.external_links:source?.layout?.external_links;if(!Array.isArray(raw))return[];const links=[],seen=new Set();for(const item of raw.slice(0,4)){if(!item||typeof item!=='object')continue;const label=String(item.label||'打开专题网页').trim().slice(0,48),value=String(item.url||'').trim();try{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||!url.hostname||seen.has(url.href))continue;seen.add(url.href);links.push({label:label||'打开专题网页',url:url.href})}catch{}}return links}
function externalLinksHTML(source,className){return compositionExternalLinks(source).map(link=>`<a class="${className}" href="${esc(link.url)}" target="_blank" rel="noopener noreferrer">${esc(link.label)}<span aria-hidden="true">↗</span></a>`).join('')}
const localId=()=>`BLC-${Date.now()}-${crypto.getRandomValues(new Uint32Array(2)).join('-')}`;
const localValue=key=>window.workspaceGetItem?.(key)??localStorage.getItem(key);
function chartVersionKey(chart){return chart?.render_fingerprint||chart?.updated_at||chart?.data_snapshot_hash||'browser-current'}
function assetKey(asset){return composer()?.assetKey?.(asset)||window.DisplayAssets?.key?.(asset)||(asset?.asset_type==='tb'?(asset.tb_page_id?`tb-page:${asset.tb_page_id}`:String(asset.asset_key||'')):String(asset?.chart_id||''))}
function itemKey(item){return window.DisplayAssets?.itemKey?.(item)||(item?.tb_page_id?`tb-page:${item.tb_page_id}`:item?.chart_id||item?.asset_key||'')}
function bindingFor(asset,location){return asset.asset_type==='tb'?{asset_type:'tb',asset_key:assetKey(asset),tb_id:asset.tb_id,tb_version_id:asset.tb_version_id,tb_page_id:asset.tb_page_id,...location}:{asset_type:'chart',chart_id:asset.chart_id,...location}}
function selectedAccess(){return document.querySelector('input[name="compositionAccess"]:checked')?.value||'private'}
function selectedCharts(){return composer()?.chartsForComposition?.()||composer()?.selectedAssets?.()||composer()?.selectedCharts?.()||[]}
function localRows(){const rows=safeJSON(localValue(LOCAL_KEY)||'[]',[]);return Array.isArray(rows)?rows:[]}
function saveLocalRows(rows){return workspaceSetItem(LOCAL_KEY,JSON.stringify(rows))}
function localFolders(){const rows=safeJSON(localValue(FOLDER_KEY)||'[]',[]);return Array.isArray(rows)?rows:[]}
function saveLocalFolders(rows){return workspaceSetItem(FOLDER_KEY,JSON.stringify(rows))}
function builtInRows(){const rows=window.GALLERY_BOOTSTRAP?.showcase_compositions;return Array.isArray(rows)?rows.map(item=>({...item,built_in:true})):[]}
function builtInFolders(){const rows=window.GALLERY_BOOTSTRAP?.showcase_folders;return Array.isArray(rows)?rows.map(item=>({...item,built_in:true})):[]}
function publicTextPayload(layout){return{title:layout.title,subtitle:layout.subtitle,sharedText:layout.sharedText,footerText:layout.footerText,...(Object.prototype.hasOwnProperty.call(layout,'itemTitles')?{itemTitles:layout.itemTitles||{}}:{}),notes:layout.notes||{},...(Object.prototype.hasOwnProperty.call(layout,'flowItems')?{flowItems:(layout.flowItems||[]).filter(item=>item?.type==='text').map(item=>({type:'text',title:item.title,text:item.text,titleFont:item.titleFont,bodyFont:item.bodyFont}))}:{}),flexPages:(layout.flexPages||[]).map(page=>({title:page.title,subtitle:page.subtitle,text1:page.text1,text2:page.text2,footnote:page.footnote})),...(Object.prototype.hasOwnProperty.call(layout,'external_links')?{external_links:compositionExternalLinks(layout)}:{})}}
function stableJSON(value){if(Array.isArray(value))return`[${value.map(stableJSON).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stableJSON(value[key])}`).join(',')}}`;return JSON.stringify(value??null)}
function publicTextSnapshot(layout){return stableJSON(publicTextPayload(layout))}
function pageBindings(charts,draft){
  if(draft.template==='ppt-flex'){
    const pageById=new Map();
    (draft.flexPages||[]).forEach((page,pageIndex)=>{
      (page.assetKeys||page.chartIds||[]).forEach((id,slot)=>{
        if(!pageById.has(id))pageById.set(id,{page_no:pageIndex+1,slot_key:`slot-${slot+1}`});
      });
    });
    return charts.map((chart,index)=>bindingFor(
      chart,pageById.get(assetKey(chart))||{page_no:1,slot_key:`slot-${index+1}`}
    ));
  }
  const pages=composer().planPages(charts,draft),location=new Map();
  pages.forEach((page,pageIndex)=>{
    (page.items||[]).forEach((item,slot)=>{
      const id=assetKey(item.chart);
      if(id&&!location.has(id))location.set(id,{page_no:pageIndex+1,slot_key:`slot-${slot+1}`});
    });
  });
  return charts.map((chart,index)=>bindingFor(
    chart,location.get(assetKey(chart))||{page_no:1,slot_key:`slot-${index+1}`}
  ));
}
function switchMode(mode){
  const browse=mode==='browse',library=mode==='library',compose=mode==='compose';
  byId('showcaseBrowsePane').hidden=!browse;byId('showcaseComposerPane').hidden=!compose;
  for(const [id,active] of [['showcaseBrowseTab',browse],['showcaseLibraryTab',library],['showcaseComposeTab',compose]]){byId(id).classList.toggle('active',active);byId(id).setAttribute('aria-selected',String(active))}
  if(compose){composer().runtime.active=true;composer().renderOrderList();composer().renderFlexEditor();composer().refreshPreview().catch(error=>setStatus(error.message,true))}else composer().runtime.active=false;
  if(library){switchView('compositionLibrary');showLibrary()}
}
function setStatus(text,error=false){const element=byId('showcaseLibraryStatus');element.textContent=text||'';element.dataset.kind=error?'error':''}
function currentRecord(){return composer()?.runtime?.currentComposition||null}
function updateCurrentUI(){
  const current=currentRecord(),boundItems=[...composer().runtime.boundItems.values()],newerItems=boundItems.filter(item=>item.has_newer_version),newerCharts=newerItems.filter(item=>item.asset_type!=='tb'&&!item.tb_page_id).length,newerTB=newerItems.length-newerCharts,historicalCharts=boundItems.filter(item=>item.asset_type!=='tb'&&!item.tb_page_id&&item.historical_time_locked).length;
  byId('composerCurrentName').textContent=current?.composition_name||'临时版式草稿';
  byId('composerVersionStatus').textContent=current?`组合 V${current.version_no||current.current_version_no||1} · ${current.access_level==='public'?'公开':'仅本地'} · 研究图默认跟随最新${historicalCharts?` · ${historicalCharts} 张固定历史时间`:''}${newerTB?` · ${newerTB} 个 TB 页有新版（仅提示）`:''}`:'尚未保存为正式组合';
  byId('composerUpgradeAll').hidden=!newerCharts;
}
function itemFolderTitle(detail,item){const key=itemKey(item),legacyKey=item?.tb_page_id||item?.chart_id;return String(detail?.layout?.itemTitles?.[key]||detail?.layout?.itemTitles?.[legacyKey]||item.folder_title||item.tb_title||item.chart_title||boundChart(item)?.title||'未命名图片')}
function itemFolderNote(detail,item){const key=itemKey(item),legacyKey=item?.tb_page_id||item?.chart_id;return String(detail?.layout?.notes?.[key]??detail?.layout?.notes?.[legacyKey]??item.folder_note??'')}
function liveInteractionURL(detail,item){
  if(item?.asset_type==='tb'||item?.tb_page_id||localMode()||!detail?.composition_id||!item?.chart_id)return'';const fingerprint=item.render_fingerprint||item.chart_version_id||'';
  return`ghgy-local:showcase-compositions/${encodeURIComponent(detail.composition_id)}/charts/${encodeURIComponent(item.chart_id)}/live-interactive${fingerprint?`?v=${encodeURIComponent(fingerprint)}`:''}`
}
function livePreviewKey(detail,item){return`${detail?.composition_id||'draft'}::${item?.tb_page_id||item?.chart_id||itemKey(item)}::${item?.render_fingerprint||item?.browser_version_key||item?.chart_version_id||item?.tb_version_id||'bound'}`}
function liveLatestSummary(chart){const ids=new Set((chart?.config?.series||[]).filter(row=>row.visible!==false).map(row=>row.indicator_id)),out={};for(const row of state.indicators||[])if(ids.has(row.indicator_id)&&row.latest_date)out[row.indicator_id]={latest_date:row.latest_date,latest_value:row.latest_value};return out}
function liveLatestDate(chart){const dates=Object.values(liveLatestSummary(chart)).map(row=>row.latest_date).filter(Boolean).sort();return dates.at(-1)||latestDate(chart)}
function chartUsesExplicitHistoricalTime(config={}){const fallback=String(config?.end_mode||'latest').trim().toLowerCase(),visible=(config?.series||[]).filter(series=>series&&series.visible!==false);return visible.length?visible.every(series=>String(series.end_mode||fallback||'latest').trim().toLowerCase()==='fixed'):fallback==='fixed'}
function researchChart(item,detail=ui.researchDetail){const chart=boundChart(item)||state.charts.find(row=>row.chart_id===item.chart_id)||null;if(!chart)return null;if(item?.asset_type==='tb'||item?.tb_page_id||item?.historical_time_locked)return chart;const liveURL=liveInteractionURL(detail,item),liveConfig=clone(chart.config||{});liveConfig.end_mode='latest';for(const series of liveConfig.series||[])if(series.visible!==false)series.end_mode='latest';const liveChart={...chart,config:liveConfig,live_data_mode:'latest',live_latest_summary:item?.packaged_latest_summary||liveLatestSummary({...chart,config:liveConfig}),live_latest_date:item?.packaged_latest_date||liveLatestDate({...chart,config:liveConfig})};if(liveURL)return{...liveChart,html_url:liveURL};if(localMode()&&chart.html_url)return{...liveChart,html_url:chart.html_url};if(localMode()&&liveConfig.series?.length)return{...liveChart,html_url:null,figure:null,interactive_figure:null};return chart}
function researchImage(item){const chart=researchChart(item);return item.bound_hd_png_url||item.bound_canonical_png_url||item.bound_png_url||localSnapshotURL(item.bound_png_data)||chart?.hd_png_url||chart?.canonical_png_url||chart?.png_url||''}
function latestDate(chart){const dates=(chart?.series_updates||[]).map(row=>row.latest_date).filter(Boolean).sort();return dates.at(-1)||''}
function chartKindText(chart){if(chart?.asset_type==='tb')return chart.tb_asset_kind==='table'?'TB 表格':'TB 截图';try{return kindLabel(chartKind(chart))}catch{return'研究图片'}}
function chartCover(id){return[...state.charts,...(window.ResearchMedia?.compositionAssets?.()||[])].find(asset=>asset.chart_id===id||asset.tb_page_id===id||assetKey(asset)===id)?.png_url||''}
function localSnapshotURL(data){return typeof data==='string'&&data.startsWith('data:image/')?data:''}
function clientPublish(record){
  if(record.access_level!=='public')return{publish_status:'not_applicable',publish_blockers:[]};
  const blockers=[];for(const item of record.items||[]){if(item.asset_type==='tb'||item.tb_page_id){const asset=(window.ResearchMedia?.compositionAssets?.()||[]).find(row=>row.tb_page_id===item.tb_page_id);if(asset?.access_level!=='public'||asset?.status!=='published')blockers.push({code:'tb_page_not_public',message:`${asset?.title||item.tb_title||'TB 页面'}不是已发布的公开资产`});continue}const chart=state.charts.find(row=>row.chart_id===item.chart_id);if(chart?.access_level!=='public'||chart?.status!=='published')blockers.push({code:'chart_not_public_data',message:`${chart?.title||item.chart_title||'图片'}不是已发布的“公开交互及数据”`})}
  const confirmation=record.layout?.public_text_confirmation;if(!confirmation?.confirmed||confirmation.text_snapshot!==publicTextSnapshot(record.layout||{}))blockers.push({code:'public_text_unconfirmed',message:'文字尚未确认可公开，或确认后文字已有变化'});return{publish_status:blockers.length?'blocked':'eligible',publish_blockers:blockers}
}
function localEffectiveItem(row,assets){if(row.asset_type==='tb'||row.tb_page_id)return row;const historical=chartUsesExplicitHistoricalTime(row.bound_config||{}),current=assets.find(asset=>assetKey(asset)===itemKey(row));if(historical||!current)return{...row,historical_time_locked:historical,auto_latest_binding:!historical};const fingerprint=current.render_fingerprint||chartVersionKey(current);return{...row,bound_config:clone(current.config||{}),bound_figure:clone(current.interactive_figure||current.figure||null),bound_series_updates:clone(current.series_updates||[]),bound_png_data:null,bound_png_url:current.canonical_png_url||current.png_url||null,bound_canonical_png_url:current.canonical_png_url||current.png_url||null,browser_version_key:fingerprint,render_fingerprint:fingerprint,historical_time_locked:false,auto_latest_binding:true,has_newer_version:false}}
function normalizeLocalCard(record){const version=record.versions?.find(item=>item.version_no===record.current_version_no)||record.versions?.at(-1)||{},rawItems=version.items||record.items||[],layout=version.layout||record.layout||{},assets=[...state.charts,...(window.ResearchMedia?.compositionAssets?.()||[])],items=rawItems.map(row=>localEffectiveItem(row,assets)),check=clientPublish({...record,items,layout}),isTBItem=item=>item.asset_type==='tb'||Boolean(item.tb_page_id);return{...record,...check,items,layout,template:layout.template||'phone-long',asset_count:items.length,chart_count:items.filter(item=>!isTBItem(item)).length,tb_page_count:items.filter(isTBItem).length,page_count:Math.max(...items.map(item=>Number(item.page_no)||1),Number(layout.flowPageCount)||1,layout.flexPages?.length||1),has_newer_version:items.some(item=>isTBItem(item)&&chartVersionKey(assets.find(asset=>assetKey(asset)===itemKey(item)))!==item.browser_version_key),historical_chart_count:items.filter(item=>!isTBItem(item)&&item.historical_time_locked).length,cover_png_urls:items.slice(0,4).map(item=>localSnapshotURL(item.bound_png_data)).filter(Boolean),cover_chart_ids:items.filter(item=>!isTBItem(item)).slice(0,4).map(item=>item.chart_id),cover_tb_page_ids:items.filter(item=>item.tb_page_id).slice(0,4).map(item=>item.tb_page_id)}}
async function loadLibrary(){
  setStatus('正在读取组合文件夹…');try{ui.library=localMode()?{folders:[...builtInFolders(),...localFolders()],compositions:[...builtInRows(),...localRows().map(normalizeLocalCard)]}:await getJSON('ghgy-local:showcase-library',{cache:'no-store'});if(ui.selectedFolder!=='all'&&!ui.library.folders.some(folder=>folder.folder_id===ui.selectedFolder&&folder.lifecycle_status!=='trashed'))ui.selectedFolder='all';renderLibrary()}catch(error){setStatus(error.message,true);byId('showcaseCompositionGrid').innerHTML='<div class="wb-contract__state" data-state="error">组合读取失败。</div>'}
}
function folderTitle(folderId){return ui.library.folders.find(folder=>folder.folder_id===folderId)?.folder_name||'未归档'}
function renderFolderFilters(){const active=(ui.library.folders||[]).filter(folder=>folder.lifecycle_status!=='trashed').sort((a,b)=>Number(Boolean(b.is_pinned))-Number(Boolean(a.is_pinned))||Number(a.sort_order||0)-Number(b.sort_order||0)||String(a.folder_name||'').localeCompare(String(b.folder_name||''),'zh-CN')),counts=new Map();for(const item of ui.library.compositions||[])if(item.lifecycle_status==='active')counts.set(item.folder_id||'',(counts.get(item.folder_id||'')||0)+1);const buttons=[`<button type="button" data-folder-filter="all" class="${ui.selectedFolder==='all'?'active':''}">全部 <span>${(ui.library.compositions||[]).filter(item=>item.lifecycle_status==='active').length}</span></button>`,`<button type="button" data-folder-filter="" class="${ui.selectedFolder===''?'active':''}">未归档 <span>${counts.get('')||0}</span></button>`,...active.map(folder=>`<button type="button" data-folder-filter="${esc(folder.folder_id)}" class="${ui.selectedFolder===folder.folder_id?'active':''}">${folder.is_pinned?'★ ':''}${esc(folder.folder_name)} <span>${counts.get(folder.folder_id)||0}</span></button>`)].join('');byId('showcaseFolderFilters').innerHTML=buttons;byId('showcaseFolderFilters').querySelectorAll('[data-folder-filter]').forEach(button=>button.onclick=()=>{ui.selectedFolder=button.dataset.folderFilter;renderLibrary()})}
function cardHTML(item){
  const covers=(item.cover_png_urls||[]).filter(Boolean).slice(0,4).concat([...(item.cover_chart_ids||[]),...(item.cover_tb_page_ids||[])].map(id=>chartCover(id)).filter(Boolean)).slice(0,4),template=TEMPLATE_LABELS[item.template]||item.template||'自定义模板',trashed=item.lifecycle_status==='trashed',builtIn=Boolean(item.built_in);
  const cover=covers.length?covers.map(url=>`<img src="${esc(url)}" loading="lazy" decoding="async" alt="">`).join(''):'<span>尚无封面</span>';
  const editable=!builtIn&&!trashed,accessLabel=item.access_level==='public'?'公开':'仅本地',accessStatus=item.access_level==='public'?'public':'';
  const accessTag=editable?`<button type="button" data-access-tag data-status="${accessStatus}" title="点击修改公开状态">${accessLabel}<span aria-hidden="true">⌄</span></button>`:`<span data-status="${accessStatus}">${accessLabel}</span>`;
  const blockedTag=item.publish_status==='blocked'?(editable?'<button type="button" data-publish-tag data-status="blocked" title="点击查看阻断原因或重新确认">不可发布<span aria-hidden="true">⌄</span></button>':'<span data-status="blocked">不可发布</span>'):'';
  const badges=[builtIn?'<span>内置公开</span>':'',item.is_pinned?'<span>置顶</span>':'',accessTag,blockedTag,item.historical_chart_count?`<span>${item.historical_chart_count} 张固定历史时间</span>`:'',item.has_newer_version?'<span data-status="newer">有图片新版</span>':''].join('');
  const externalLinks=externalLinksHTML(item,'showcase-composition-link-v6');
  const actions=builtIn?`<button data-open data-primary>打开观看</button><button data-compose>排版与导出</button><button data-copy>复制到本机</button>`:trashed?`<button data-restore>恢复</button><button data-delete data-danger>彻底删除</button>`:`<button data-open data-primary>打开观看</button><button data-compose>排版与导出</button><button data-move>移动文件夹</button><button data-pin>${item.is_pinned?'取消置顶':'置顶'}</button><button data-rename>改名</button><button data-copy>复制</button><button data-trash data-danger>移入回收箱</button>`;
  return`<article class="showcase-composition-card-v4" data-composition-id="${esc(item.composition_id)}"><div class="showcase-composition-cover-v4">${cover}</div><div class="showcase-composition-body-v4"><div class="showcase-composition-title-v4"><h3>${esc(item.composition_name)}</h3><time>${esc(String(item.updated_at||'').slice(0,16).replace('T',' '))}</time></div><div class="showcase-composition-meta-v4"><span>${esc(template)}</span><span>${item.chart_count||0} 研究图</span><span>${item.tb_page_count||0} TB 页</span><span>${item.page_count||1} 排版页</span><span>${esc(item.built_in?'内置公开':folderTitle(item.folder_id))}</span></div><div class="showcase-composition-badges-v4">${badges}</div>${externalLinks?`<div class="showcase-composition-links-v6">${externalLinks}</div>`:''}<div class="showcase-composition-actions-v4">${actions}</div></div></article>`
}
function renderLibrary(){
  renderFolderFilters();const allRows=ui.library.compositions.filter(item=>item.lifecycle_status===(ui.trash?'trashed':'active')).filter(item=>ui.trash||ui.selectedFolder==='all'||(item.folder_id||'')===ui.selectedFolder).sort((a,b)=>Number(Boolean(b.is_pinned))-Number(Boolean(a.is_pinned))||String(b.updated_at||'').localeCompare(String(a.updated_at||''))||String(a.composition_id).localeCompare(String(b.composition_id))),query=ui.libraryQuery.trim().toLocaleLowerCase('zh-CN'),rows=query?allRows.filter(item=>String(item.composition_name||'').toLocaleLowerCase('zh-CN').includes(query)):allRows,clear=byId('showcaseLibrarySearchClear');
  if(clear)clear.hidden=!query;setStatus(query?`${rows.length} / ${allRows.length} 个组合`:`${allRows.length} 个组合`);
  byId('showcaseCompositionGrid').innerHTML=rows.map(cardHTML).join('')||`<div class="wb-contract__state">${query?`没有标题匹配“${esc(ui.libraryQuery.trim())}”的组合。`:ui.trash?'回收箱为空。':'还没有保存组合；当前临时草稿会自动迁移一次。'}</div>`;
  byId('showcaseLibraryActive').classList.toggle('wb-contract__button--primary',!ui.trash);byId('showcaseLibraryTrash').classList.toggle('wb-contract__button--primary',ui.trash);
  byId('showcaseCompositionGrid').querySelectorAll('[data-composition-id]').forEach(card=>bindCard(card,rows.find(item=>item.composition_id===card.dataset.compositionId)))
}
function localDetail(id){const record=localRows().find(item=>item.composition_id===id);if(!record)throw new Error('找不到该本机组合。');return normalizeLocalCard(record)}
async function detailFor(item){return localMode()?(item.built_in?clone(item):localDetail(item.composition_id)):getJSON(`ghgy-local:showcase-compositions/${encodeURIComponent(item.composition_id)}`,{cache:'no-store'})}
function boundChart(item){if(item.asset_type==='tb'||item.tb_page_id){const current=(window.ResearchMedia?.compositionAssets?.()||[]).find(asset=>asset.tb_page_id===item.tb_page_id),image=localSnapshotURL(item.bound_png_data)||item.bound_hd_png_url||item.bound_canonical_png_url||item.bound_png_url||current?.hd_png_url||current?.png_url,key=itemKey(item);return{...(current||{}),asset_key:key,title:item.tb_title||current?.title||'未命名 TB 页面',source_title:item.tb_title||current?.source_title,asset_type:'tb',tb_id:item.tb_id,tb_version_id:item.tb_version_id,tb_page_id:item.tb_page_id,tb_asset_kind:item.tb_asset_kind||current?.tb_asset_kind,domain:'表格与截图',categories:[(item.tb_asset_kind||current?.tb_asset_kind)==='table'?'表格':'截图'],config:item.bound_config||{},access_level:item.tb_access_level||current?.access_level,status:item.tb_publication_status||current?.status,render_fingerprint:item.render_fingerprint||item.browser_version_key,png_url:image,canonical_png_url:image,hd_png_url:image,html_url:null,series_updates:[],immutable_bound:true,page_no:Number(item.tb_page_no||current?.page_no)||1,page_count:Number(item.tb_page_count||current?.page_count)||null}}const current=state.charts.find(chart=>chart.chart_id===item.chart_id),base=current||{chart_id:item.chart_id,title:item.chart_title||item.bound_config?.title||'未命名图片',domain:item.bound_config?.domain||'未分类',config:item.bound_config||{},access_level:item.chart_access_level};if(!item.bound_config)return current;const sameCurrentVersion=Boolean(current?.render_fingerprint&&(current.render_fingerprint===item.render_fingerprint||current.render_fingerprint===item.browser_version_key)),hasBoundHTML=Object.prototype.hasOwnProperty.call(item,'bound_html_url'),boundPNG=localSnapshotURL(item.bound_png_data)||item.bound_png_url||item.bound_canonical_png_url,boundFigure=item.bound_figure||(sameCurrentVersion?(current?.interactive_figure||current?.figure):null),boundHTML=hasBoundHTML?item.bound_html_url:(sameCurrentVersion?current?.html_url:null),updates=Array.isArray(item.bound_series_updates)?item.bound_series_updates:(sameCurrentVersion?(current?.series_updates||[]):[]);return{...base,title:item.chart_title||item.bound_config.title||base.title,config:item.bound_config,render_fingerprint:item.render_fingerprint||item.browser_version_key,html_url:boundHTML,png_url:boundPNG||(sameCurrentVersion?current?.png_url:null),canonical_png_url:item.bound_canonical_png_url||boundPNG||(sameCurrentVersion?current?.canonical_png_url:null),figure:boundFigure,interactive_figure:boundFigure,series_updates:updates,immutable_bound:true,historical_time_locked:Boolean(item.historical_time_locked),auto_latest_binding:Boolean(item.auto_latest_binding),bound_snapshot_error:item.bound_snapshot_error||null}}
async function chartSnapshot(chart,existing){if(existing?.bound_config)return clone(existing);const source=chart.asset_type==='tb'?(chart.hd_png_url||chart.png_url||chart.canonical_png_url||''):(chart.canonical_png_url||chart.png_url||''),snapshot={bound_config:clone(chart.config||{}),bound_figure:clone(chart.figure||chart.interactive_figure||null),bound_series_updates:clone(chart.series_updates||[]),bound_png_data:source.startsWith('data:image/')?source:null};if(source&&!snapshot.bound_png_data&&window.GHGY_WORKSPACE?.snapshotImage){try{snapshot.bound_png_data=await window.GHGY_WORKSPACE.snapshotImage(source)}catch(error){console.warn('组合图片快照未写入，已保留配置与版本键',error)}}return snapshot}
function loadCompositionContext(detail){
  const items=detail.items||[],ids=items.map(itemKey).filter(Boolean),assets=items.map(row=>[itemKey(row),boundChart(row)]).filter(([,asset])=>asset);state.showcase=new Set(ids);workspaceSetItem('yd-showcase',JSON.stringify(ids));workspaceSetItem(ORDER_KEY,JSON.stringify(ids));composer().runtime.boundItems=new Map(items.map(row=>[itemKey(row),row]));composer().runtime.boundAssets=new Map(assets);composer().runtime.boundCharts=new Map(assets.filter(([,asset])=>asset.asset_type!=='tb'));composer().runtime.currentComposition=detail;composer().loadDraft(detail.layout||{});updateCurrentUI();return detail
}
function researchCardHTML(detail,item,index){
  const liveKey=livePreviewKey(detail,item),fresh=ui.livePreviewCharts.get(liveKey),chart=fresh||researchChart(item,detail),image=researchImage(item),title=chart?.asset_type==='tb'?itemFolderTitle(detail,item):chartDisplayTitle(chart,itemFolderTitle(detail,item)),note=itemFolderNote(detail,item),newer=Boolean(item.has_newer_version),historical=Boolean(item.historical_time_locked),canInteract=Boolean(chart?.live_data_mode==='latest'&&chart?.config?.series?.length||chart?.html_url||chart?.interactive_figure||chart?.figure),version=item.bound_version_no||item.version_no||'—',live=Boolean(fresh?.live_data_mode==='latest'&&fresh?.live_card_png_url),packagedLatest=item?.packaged_data_mode==='latest',date=live?(chart.live_latest_date||liveLatestDate(chart)):(item?.packaged_latest_date||latestDate(boundChart(item))),dataLabel=historical?(date?`固定历史时间 · 数据至 ${date}`:'固定历史时间'):live?(date?`当前最新画面 · 数据至 ${date}`:'当前最新画面'):packagedLatest?(date?`当前最新画面 · 数据至 ${date}`:'当前最新画面'):(date?`当前最新画面 · 数据至 ${date}`:'当前最新画面');
  const visual=live?`<img class="composition-research-fallback-v8" src="${esc(fresh.live_card_png_url)}" loading="lazy" decoding="async" alt="${esc(title)}最新数据高清画面"><iframe data-composition-live-interactive="${esc(liveKey)}" title="${esc(title)}最新数据交互预览"></iframe>`:(image?`<img src="${esc(image)}" loading="lazy" decoding="async" alt="${esc(title)}">`:'<div class="wb-contract__state">该绑定版本暂无静态预览。</div>');
  return`<article class="composition-research-card-v5${newer?' has-newer':''}${live?' is-live':''}" data-research-chart="${esc(itemKey(item))}"><div class="composition-research-visual-v5">${visual}<div class="composition-research-index-v5">${String(index+1).padStart(2,'0')}</div>${live?'<span class="composition-research-live-v5">可悬停 · 最新数据</span>':newer?'<span class="composition-research-newer-v5">有新版</span>':''}</div><div class="composition-research-card-body-v5"><div class="composition-research-card-heading-v5"><div><h3>${esc(title)}</h3><p>${esc(chartKindText(chart))} · ${esc(chart?.domain||'未分类')} · ${esc(chart?.asset_type==='tb'?'精确绑定 TB 页面':dataLabel)}</p></div><span>版本 ${esc(item.tb_version_id||`V${version}`)}</span></div><div class="composition-research-note-v5"><div><strong>本组合文字</strong><span>仅当前文件夹</span></div><p class="${note?'':'is-empty'}">${esc(note||'点击“编辑标题与文字”，记录这张图在当前研究主题里的判断。')}</p></div><div class="composition-research-card-actions-v5"><button class="wb-contract__button wb-contract__button--primary" data-interactive ${canInteract?'':'disabled title="该绑定版本没有可用交互资源"'}>${live?'放大交互':'交互预览'}</button><button class="wb-contract__button" data-edit-text ${detail.built_in?'disabled title="内置公开组合请先复制到本机"':''}>编辑标题与文字</button><span>第 ${Number(item.page_no)||1} 页 · 顺序 ${index+1}</span></div></div></article>`
}
function renderResearchExternalLinks(detail){const root=byId('compositionResearchExternalLinks');if(!root)return;const html=externalLinksHTML(detail||{},'composition-research-external-link-v6');root.hidden=!html;root.innerHTML=html}
function renderResearch(){
  renderResearchExternalLinks(ui.researchDetail);
  const detail=ui.researchDetail;if(!detail)return;const all=detail.items||[],rows=ui.researchFilter==='newer'?all.filter(item=>item.has_newer_version):all,newerItems=all.filter(item=>item.has_newer_version),newer=newerItems.length,newerTB=newerItems.filter(item=>item.asset_type==='tb'||item.tb_page_id).length,newerCharts=newer-newerTB,historicalCharts=all.filter(item=>item.asset_type!=='tb'&&!item.tb_page_id&&item.historical_time_locked).length;byId('compositionResearchName').textContent=detail.composition_name||'未命名组合';byId('compositionResearchMeta').textContent=`组合 V${detail.version_no||detail.current_version_no||1} · ${TEMPLATE_LABELS[detail.layout?.template]||detail.layout?.template||'自定义模板'} · ${all.length} 个展示资产 · ${detail.access_level==='public'?'公开':'仅本地'} · 研究图默认跟随最新${historicalCharts?` · ${historicalCharts} 张固定历史时间`:''}`;byId('compositionResearchCount').textContent=`${rows.length} / ${all.length} 个展示资产`;byId('compositionResearchAll').classList.toggle('wb-contract__button--primary',ui.researchFilter==='all');byId('compositionResearchNewer').classList.toggle('wb-contract__button--primary',ui.researchFilter==='newer');byId('compositionResearchNewer').textContent=`有新版${newer?` ${newer}`:''}`;const notice=byId('compositionResearchUpdateNotice');notice.hidden=!newer;notice.textContent=newer?[newerCharts?`${newerCharts} 张研究图已有新版，可在排版工作区显式选择升级。`:'',newerTB?`${newerTB} 个 TB 页已有新版；当前组合仍精确绑定旧版页，系统只提示，绝不自动替换。`:''].filter(Boolean).join(' '):'';const grid=byId('compositionResearchGrid');grid.querySelectorAll('[data-composition-live-interactive]').forEach(frame=>window.disposeCompositionLatestPreview?.(frame));grid.innerHTML=rows.map((item,index)=>researchCardHTML(detail,item,index)).join('')||'<div class="wb-contract__state">当前筛选没有展示资产。</div>';grid.querySelectorAll('[data-research-chart]').forEach(card=>{const item=all.find(row=>itemKey(row)===card.dataset.researchChart),fresh=ui.livePreviewCharts.get(livePreviewKey(detail,item)),liveFrame=card.querySelector('[data-composition-live-interactive]');if(liveFrame&&fresh?.live_card_figure)window.mountCompositionLatestPreview?.(fresh,liveFrame).then(()=>liveFrame.classList.add('is-ready')).catch(error=>{console.warn('组合卡片交互层未通过校验，继续显示高清静态兜底。',error);card.querySelector('.composition-research-live-v5').textContent='高清最新画面';liveFrame.remove()});card.querySelector('[data-interactive]')?.addEventListener('click',()=>{if(item.asset_type==='tb'||item.tb_page_id)return;const chart=researchChart(item,detail);if(!chart)return;window.openCompositionChartViewer?.(chart,{title:itemFolderTitle(detail,item),note:itemFolderNote(detail,item),version:item.bound_version_no||item.version_no,latestDate:chart.live_latest_date||liveLatestDate(chart),onLiveActivated:preview=>ui.livePreviewCharts.set(livePreviewKey(detail,item),preview)})});card.querySelector('[data-edit-text]')?.addEventListener('click',()=>openResearchText(item))})
}

function setBatchPreviewStatus(text,error=false){const status=byId('compositionResearchBatchStatus');status.hidden=!text;status.textContent=text||'';status.dataset.kind=error?'error':''}
async function activateAllResearch(){
  const detail=ui.researchDetail,button=byId('compositionResearchActivateAll');if(!detail||button.disabled)return;const all=detail.items||[],items=all.filter(item=>item.asset_type!=='tb'&&!item.tb_page_id&&!item.historical_time_locked),tbCount=all.filter(item=>item.asset_type==='tb'||item.tb_page_id).length,historicalCount=all.filter(item=>item.asset_type!=='tb'&&!item.tb_page_id&&item.historical_time_locked).length,run=++ui.previewRun,failures=[];if(!items.length)return setBatchPreviewStatus(historicalCount?`${historicalCount} 张研究图已固定历史时间，不切换到最新观看态。`:tbCount?'当前组合只有 TB 静态页，无需加载图表交互。':'当前组合没有可预览资产。');button.disabled=true;button.textContent='正在准备 0 / '+items.length;setBatchPreviewStatus(`正在读取 ${items.length} 张研究图的最新数据；${historicalCount?`${historicalCount} 张固定历史时间，`:''}${tbCount} 个 TB 页保持绑定 PNG…`);
  try{
    for(let start=0;start<items.length;start+=2){
      if(run!==ui.previewRun)return;const batch=items.slice(start,start+2);
      const results=await Promise.allSettled(batch.map(async item=>{const chart=researchChart(item,detail);if(!chart)throw new Error('缺少绑定图片');const preview=await window.loadCompositionLatestPreview(chart);return{item,preview}}));
      results.forEach((result,index)=>{const item=batch[index];if(result.status==='fulfilled')ui.livePreviewCharts.set(livePreviewKey(detail,item),result.value.preview);else{ui.livePreviewCharts.delete(livePreviewKey(detail,item));failures.push(`${itemFolderTitle(detail,item)}：${result.reason?.message||'加载失败'}`)}});
      const completed=Math.min(start+batch.length,items.length);button.textContent=`正在准备 ${completed} / ${items.length}`;renderResearch();setBatchPreviewStatus(`已完成 ${completed} / ${items.length} 张；成功的卡片已显示“最新数据”。`)
    }
    renderResearch();setBatchPreviewStatus(failures.length?`${items.length-failures.length} 张研究图已进入最新观看态；${failures.length} 张保留绑定画面：${failures.join('；')}`:`${items.length} 张研究图已全部进入最新观看态；${historicalCount?`${historicalCount} 张固定历史时间；`:''}${tbCount} 个 TB 页保持原绑定 PNG。`,Boolean(failures.length))
  }catch(error){setBatchPreviewStatus(error.message||'一键交互预览失败。',true)}finally{if(run===ui.previewRun){button.disabled=false;button.textContent='一键交互预览'}}
}
function showResearchPane(scroll=true){byId('showcaseLibraryPane').hidden=true;byId('compositionResearchPane').hidden=false;renderResearch();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
async function openComposition(item){try{setStatus('正在打开组合…');const detail=await detailFor(item);ui.researchDetail=detail;ui.researchFilter='all';showResearchPane();setStatus('')}catch(error){setStatus(error.message,true)}}
async function openCompositionForComposer(item=ui.researchDetail){try{setStatus('正在进入排版工作区…');const detail=item?.layout&&item?.items?item:await detailFor(item);loadCompositionContext(detail);switchView('showcase');switchMode('compose');setStatus('')}catch(error){setStatus(error.message,true)}}
function showLibrary(){ui.researchDetail=null;byId('showcaseLibraryPane').hidden=false;byId('compositionResearchPane').hidden=true;loadLibrary()}
function restoreResearchView(){const detail=ui.researchDetail;switchView('compositionLibrary');if(detail){ui.researchDetail=detail;showResearchPane(false)}}
async function refreshResearch(){if(!ui.researchDetail)return;try{const detail=await detailFor(ui.researchDetail);ui.researchDetail=detail;renderResearch()}catch(error){setStatus(error.message,true)}}
function openResearchText(item){const detail=ui.researchDetail;if(!detail||detail.built_in)return;loadCompositionContext(detail);ui.researchItem=item;const source=boundChart(item),key=itemKey(item);byId('compositionResearchTextHeading').textContent=itemFolderTitle(detail,item);byId('compositionResearchItemTitle').value=String(detail.layout?.itemTitles?.[key]||'');byId('compositionResearchItemNote').value=itemFolderNote(detail,item);byId('compositionResearchSourceNote').textContent=String(source?.note_text||'').trim()||'尚未填写原始说明。';byId('compositionResearchTextStatus').textContent='保存后生成组合新版本；研究图库原图与 TB 页面保持不变。';byId('compositionResearchTextDialog').showModal()}
async function saveResearchText(event){event.preventDefault();const detail=ui.researchDetail,item=ui.researchItem;if(!detail||!item||detail.built_in)return;const button=byId('compositionResearchTextSave');try{button.disabled=true;const key=itemKey(item),title=byId('compositionResearchItemTitle').value.trim(),note=byId('compositionResearchItemNote').value;composer().runtime.draft.itemTitles={...(composer().runtime.draft.itemTitles||{})};composer().runtime.draft.notes={...(composer().runtime.draft.notes||{})};if(title)composer().runtime.draft.itemTitles[key]=title;else delete composer().runtime.draft.itemTitles[key];composer().runtime.draft.notes[key]=note;const saved=await saveComposition(detail.composition_name,detail.access_level,false);loadCompositionContext(saved);ui.researchDetail=saved;ui.researchItem=null;byId('compositionResearchTextDialog').close();renderResearch();loadLibrary();setStatus(saved.access_level==='public'?'组合文字已保存为新版本；公开文字确认已失效，重新确认前不会进入客户包。':'组合文字已保存为新版本。')}catch(error){byId('compositionResearchTextStatus').textContent=error.message}finally{button.disabled=false}}
async function formalBindings(charts){const ids=charts.filter(chart=>chart.asset_type!=='tb').map(chart=>chart.chart_id);if(!ids.length)return{};const result=await getJSON(`ghgy-local:chart-version-bindings?${new URLSearchParams({ids:ids.join(',')})}`,{cache:'no-store'});return result.items||{}}
async function savePayload(name,access,confirmPublic,{saveAs=false,migration=false}={}){
  const draft=composer().serializeDraft(),charts=selectedCharts();if(!charts.length)throw new Error('组合至少需要一张图片。');
  const pages=pageBindings(charts,draft),current=saveAs?null:currentRecord();if(confirmPublic){draft.public_text_confirmation={confirmed:true,confirmed_at:now(),text_snapshot:publicTextSnapshot(draft)}}
  if(localMode()){const items=[];for(const binding of pages){const key=binding.asset_type==='tb'?binding.asset_key:binding.chart_id,existing=composer().runtime.boundItems.get(key),chart=charts.find(row=>assetKey(row)===key),snapshot=await chartSnapshot(chart,existing);items.push({...binding,...snapshot,...(chart.asset_type==='tb'?{tb_title:chart.source_title||chart.title,tb_asset_kind:chart.tb_asset_kind||chart.categories?.[0],tb_page_no:Number(chart.page_no)||1,tb_page_count:Number(chart.page_count)||1,browser_version_key:existing?.browser_version_key||chartVersionKey(chart)}:{chart_title:chart.title,browser_version_key:existing?.browser_version_key||chartVersionKey(chart),chart_access_level:chart.access_level})})}return{draft,charts,pages,current,items}}
  const latest=await formalBindings(charts);return{draft,charts,pages,current,items:pages.map(binding=>{const key=binding.asset_type==='tb'?binding.asset_key:binding.chart_id,existing=composer().runtime.boundItems.get(key);if(binding.asset_type==='tb'){const bound=existing?.tb_page_id?existing:binding;if(!bound.tb_id||!bound.tb_version_id||!bound.tb_page_id)throw new Error(`TB 页面缺少可绑定的正式版本：${key}`);const{asset_key,...payload}=binding;return{...payload,tb_id:bound.tb_id,tb_version_id:bound.tb_version_id,tb_page_id:bound.tb_page_id}}const bound=existing?.chart_version_id?existing:latest[binding.chart_id];if(!bound?.chart_version_id||!bound?.render_fingerprint)throw new Error(`图片缺少可绑定的正式版本：${binding.chart_id}`);return{...binding,chart_version_id:bound.chart_version_id,render_fingerprint:bound.render_fingerprint}}),migration}
}
async function saveLocalComposition(name,access,confirmPublic,prepared,{saveAs=false,migration=false}={}){
  const rows=localRows(),existing=prepared.current&&!saveAs?rows.find(item=>item.composition_id===prepared.current.composition_id):null,stamp=now(),id=existing?.composition_id||localId(),versionNo=(existing?.current_version_no||0)+1,layout=prepared.draft,folderId=byId('compositionFolder')?.value||null;const version={version_no:versionNo,layout,items:prepared.items,created_at:stamp},record={...(existing||{}),composition_id:id,folder_id:folderId,composition_name:name,access_level:access,is_pinned:existing?.is_pinned||false,lifecycle_status:'active',metadata_revision:(existing?.metadata_revision||0)+1,created_at:existing?.created_at||stamp,updated_at:stamp,current_version_no:versionNo,versions:[...(existing?.versions||[]),version],migration_source_key:migration?MIGRATION_KEY:existing?.migration_source_key};if(existing)rows.splice(rows.indexOf(existing),1,record);else rows.push(record);await saveLocalRows(rows);return normalizeLocalCard(record)
}
async function saveComposition(name,access,confirmPublic,options={}){
  const prepared=await savePayload(name,access,confirmPublic,options);if(localMode())return await saveLocalComposition(name,access,confirmPublic,prepared,options);
  const current=prepared.current&&!options.saveAs?prepared.current:null,payload={composition_id:current?.composition_id,expected_revision:current?.metadata_revision,composition_name:name,folder_id:byId('compositionFolder')?.value||null,access_level:access,is_pinned:Boolean(current?.is_pinned),layout:prepared.draft,items:prepared.items,public_text_confirmed:confirmPublic,migration_source_key:options.migration?MIGRATION_KEY:undefined};const result=await getJSON('ghgy-local:showcase-compositions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return getJSON(`ghgy-local:showcase-compositions/${encodeURIComponent(result.composition_id)}`,{cache:'no-store'})
}
function openSaveDialog(saveAs=false){const current=currentRecord(),copyBuiltIn=Boolean(current?.built_in);ui.saveAs=saveAs||copyBuiltIn;byId('compositionSaveHeading').textContent=ui.saveAs?(copyBuiltIn?'另存为本机组合':'另存为新组合'):current?'保存组合新版本':'保存新组合';byId('compositionName').value=ui.saveAs?`${current?.composition_name||composer().runtime.draft.title||'未命名组合'} 副本`:(current?.composition_name||composer().runtime.draft.title||'未命名组合');const folder=byId('compositionFolder'),folders=(ui.library.folders||[]).filter(item=>item.lifecycle_status!=='trashed');folder.innerHTML='<option value="">未归档</option>'+folders.map(item=>`<option value="${esc(item.folder_id)}">${esc(item.folder_name)}</option>`).join('');folder.value=copyBuiltIn?'':(current?.folder_id||(ui.selectedFolder==='all'?'':ui.selectedFolder));const access=copyBuiltIn?'private':(current?.access_level||'private');document.querySelector(`input[name="compositionAccess"][value="${access}"]`).checked=true;byId('compositionPublicConfirm').checked=false;togglePublicConfirm();byId('compositionSaveMessage').textContent='';byId('compositionSaveDialog').showModal()}
function togglePublicConfirm(){byId('compositionPublicConfirmWrap').hidden=selectedAccess()!=='public'}
async function confirmSave(event){event.preventDefault();const name=byId('compositionName').value.trim(),access=selectedAccess(),confirmed=byId('compositionPublicConfirm').checked;if(!name)return void(byId('compositionSaveMessage').textContent='请输入组合名称。');if(access==='public'&&!confirmed)return void(byId('compositionSaveMessage').textContent='公开组合必须确认全部文字可公开。');try{byId('compositionSaveConfirm').disabled=true;const detail=await saveComposition(name,access,confirmed,{saveAs:ui.saveAs});loadCompositionContext(detail);byId('compositionSaveDialog').close();setStatus(detail.publish_status==='blocked'?`组合已保存，但不可发布：${(detail.publish_blockers||[]).map(row=>row.message).join('；')}`:'组合已保存。',detail.publish_status==='blocked');loadLibrary()}catch(error){byId('compositionSaveMessage').textContent=error.message}finally{byId('compositionSaveConfirm').disabled=false}}
async function metadata(item,changes){if(localMode()){const rows=localRows(),row=rows.find(value=>value.composition_id===item.composition_id);if(!row)throw new Error('找不到组合。');const safeChanges={...changes};delete safeChanges.permission_change_confirmation;Object.assign(row,safeChanges,{metadata_revision:(row.metadata_revision||0)+1,updated_at:now()});await saveLocalRows(rows);return}await getJSON(`ghgy-local:showcase-compositions/${encodeURIComponent(item.composition_id)}/metadata`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:item.metadata_revision,...changes})})}
function permissionConfirmation(target){return{first:true,second:true,target_access_level:target,source:'composition_status_tag'}}
function quickAccessTarget(){return document.querySelector('input[name="compositionQuickAccess"]:checked')?.value||'private'}
function openAccessDialog(item,mode='toggle'){
  if(!item||item.built_in||item.lifecycle_status==='trashed')return;
  ui.accessItem=item;ui.accessMode=mode;
  const target=item.access_level;
  const radio=document.querySelector(`input[name="compositionQuickAccess"][value="${target}"]`);if(radio)radio.checked=true;
  byId('compositionAccessHeading').textContent=mode==='blocked'?'处理不可发布状态':'修改组合公开状态';
  byId('compositionAccessName').textContent=`“${item.composition_name}”当前为${item.access_level==='public'?'公开':'仅本地'}。`;
  const blockers=item.publish_blockers||[];byId('compositionAccessBlockers').hidden=!blockers.length;byId('compositionAccessBlockers').textContent=blockers.length?`当前阻断：${blockers.map(row=>row.message).join('；')}`:'';
  byId('compositionAccessConfirmFirst').checked=false;byId('compositionAccessConfirmSecond').checked=false;byId('compositionAccessStatus').textContent='';
  updateAccessDialog();byId('compositionAccessDialog').showModal();
}
function updateAccessDialog(){
  const item=ui.accessItem;if(!item)return;const target=quickAccessTarget(),toPublic=target==='public',same=target===item.access_level,textBlocked=(item.publish_blockers||[]).some(row=>row.code==='public_text_unconfirmed'),folderBlocked=(item.publish_blockers||[]).some(row=>row.code==='folder_not_approved_for_public_release'),canReconfirm=same&&toPublic&&ui.accessMode==='blocked'&&textBlocked,canPublishFolder=same&&toPublic&&ui.accessMode==='blocked'&&folderBlocked,noAction=same&&!canReconfirm&&!canPublishFolder;
  byId('compositionAccessImpact').textContent=noAction?`当前已经是${toPublic?'公开':'仅本地'}；如需修改，请选择另一项。`:canPublishFolder?'这个组合已公开，但所属文件夹仍是仅本地。两次确认后会联动公开文件夹，使其中已公开的组合真正进入下次 GitHub 候选；私有组合仍不会公开。':toPublic?'公开后会进入下一次本地 GitHub 构建候选，但不会立即上传或替换固定网址。':'改为仅本地后，不再进入下一次公开构建候选。';
  byId('compositionAccessConfirmFirstText').textContent=toPublic?'我已核对这个组合内图片与文字的公开范围':'我确认这个组合应改为仅本地';
  byId('compositionAccessConfirmSecondText').textContent=toPublic?'我再次确认标题、正文、逐图说明和页下注均可公开':'我再次确认它不再进入下次公开候选';
  for(const checkbox of [byId('compositionAccessConfirmFirst'),byId('compositionAccessConfirmSecond')]){checkbox.disabled=noAction;checkbox.closest('label').hidden=noAction}
  const nonTextBlockers=(item.publish_blockers||[]).filter(row=>row.code!=='public_text_unconfirmed');
  if(noAction)byId('compositionAccessStatus').textContent='当前状态不会改变。';
  else if(toPublic&&nonTextBlockers.length)byId('compositionAccessStatus').textContent=`注意：确认文字后仍有其他阻断：${nonTextBlockers.map(row=>row.message).join('；')}`;
  else byId('compositionAccessStatus').textContent=canReconfirm?'两次确认后会保存一个内容不变的确认版本。':'';
  byId('compositionAccessApply').textContent=noAction?'请选择新状态':canPublishFolder?'公开所属文件夹':canReconfirm?'重新确认公开文字':toPublic?'确认改为公开':'确认改为仅本地';
  byId('compositionAccessApply').disabled=noAction||!byId('compositionAccessConfirmFirst').checked||!byId('compositionAccessConfirmSecond').checked;
}
function changeQuickAccessTarget(){byId('compositionAccessConfirmFirst').checked=false;byId('compositionAccessConfirmSecond').checked=false;updateAccessDialog()}
async function changeLocalAccess(item,target){
  const rows=localRows(),row=rows.find(value=>value.composition_id===item.composition_id);if(!row)throw new Error('找不到组合。');const stamp=now();
  if(target==='public'){
    const source=row.versions?.find(value=>value.version_no===row.current_version_no)||row.versions?.at(-1)||{layout:row.layout||{},items:row.items||[]},layout=clone(source.layout||{}),versionNo=(row.current_version_no||0)+1;
    layout.public_text_confirmation={confirmed:true,confirmed_at:stamp,text_snapshot:publicTextSnapshot(layout)};
    row.versions=[...(row.versions||[]),{version_no:versionNo,layout,items:clone(source.items||[]),created_at:stamp}];row.current_version_no=versionNo;
  }
  row.access_level=target;row.metadata_revision=(row.metadata_revision||0)+1;row.updated_at=stamp;await saveLocalRows(rows);return normalizeLocalCard(row);
}
async function confirmPublicAccess(item){
  if(localMode())return changeLocalAccess(item,'public');
  const detail=await detailFor(item),folderBlocked=(item.publish_blockers||[]).some(row=>row.code==='folder_not_approved_for_public_release'),textBlocked=(item.publish_blockers||[]).some(row=>row.code==='public_text_unconfirmed');
  if(folderBlocked){const folder=(ui.library.folders||[]).find(row=>row.folder_id===detail.folder_id);if(!folder)throw new Error('组合所属文件夹已不存在，请先刷新。');await getJSON(`ghgy-local:showcase-folders/${encodeURIComponent(folder.folder_id)}/metadata`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:folder.metadata_revision,folder_name:folder.folder_name,sort_order:folder.sort_order,is_pinned:Boolean(folder.is_pinned),pin_rank:folder.pin_rank,access_level:'public',permission_change_confirmation:permissionConfirmation('public')})});if(item.access_level==='public'&&!textBlocked)return getJSON(`ghgy-local:showcase-compositions/${encodeURIComponent(item.composition_id)}`,{cache:'no-store'})}
  const payload={composition_id:detail.composition_id,expected_revision:detail.metadata_revision,composition_name:detail.composition_name,folder_id:detail.folder_id||null,access_level:'public',is_pinned:Boolean(detail.is_pinned),pin_rank:detail.pin_rank,layout:detail.layout,items:detail.items,public_text_confirmed:true,permission_change_confirmation:permissionConfirmation('public')};
  const saved=await getJSON('ghgy-local:showcase-compositions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});return getJSON(`ghgy-local:showcase-compositions/${encodeURIComponent(saved.composition_id)}`,{cache:'no-store'});
}
async function applyAccessChange(event){
  event.preventDefault();const item=ui.accessItem;if(!item)return;const target=quickAccessTarget(),button=byId('compositionAccessApply');if(button.disabled)return;
  try{button.disabled=true;byId('compositionAccessStatus').textContent='正在保存…';let detail;if(target==='public')detail=await confirmPublicAccess(item);else if(localMode())detail=await changeLocalAccess(item,'private');else await metadata(item,{access_level:'private',permission_change_confirmation:permissionConfirmation('private')});byId('compositionAccessDialog').close();await loadLibrary();const blocked=detail?.publish_status==='blocked';setStatus(blocked?`公开状态已保存，但仍不可发布：${(detail.publish_blockers||[]).map(row=>row.message).join('；')}`:target==='public'?'已完成两次确认，组合现在可按校验结果进入下次公开候选。':'组合已改为仅本地。',blocked)}catch(error){byId('compositionAccessStatus').textContent=error.message;button.disabled=false}
}
async function lifecycle(item,status){if(localMode()){const rows=localRows(),row=rows.find(value=>value.composition_id===item.composition_id);if(!row)throw new Error('找不到组合。');Object.assign(row,{lifecycle_status:status,trashed_at:status==='trashed'?now():null,metadata_revision:(row.metadata_revision||0)+1,updated_at:now()});await saveLocalRows(rows);return}await getJSON(`ghgy-local:showcase-library/composition/${encodeURIComponent(item.composition_id)}/lifecycle`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:item.metadata_revision,lifecycle_status:status})})}
async function permanentDelete(item){if(!confirm(`彻底删除“${item.composition_name}”？原始图片、图片说明和指标不会删除。`))return;if(!confirm('第二次确认：只删除这个组合及其排版历史，且无法恢复。'))return;if(localMode()){await saveLocalRows(localRows().filter(row=>row.composition_id!==item.composition_id));return}await getJSON(`ghgy-local:showcase-compositions/${encodeURIComponent(item.composition_id)}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:item.metadata_revision})})}
async function copyComposition(item){const detail=await detailFor(item);if(localMode()){const rows=localRows(),stamp=now(),source=rows.find(row=>row.composition_id===item.composition_id),layout=clone(detail.layout||{}),assets=[...state.charts,...(window.ResearchMedia?.compositionAssets?.()||[])],items=clone(detail.items||[]).map(row=>{const current=assets.find(asset=>assetKey(asset)===itemKey(row));return{...row,browser_version_key:row.has_newer_version?(row.browser_version_key||row.render_fingerprint||'bound-older-version'):chartVersionKey(current)}}),version={version_no:1,layout,items,created_at:stamp},copy=source?{...clone(source),composition_id:localId(),composition_name:`${item.composition_name} 副本`,access_level:'private',is_pinned:false,lifecycle_status:'active',metadata_revision:1,created_at:stamp,updated_at:stamp,current_version_no:1,versions:[version],migration_source_key:null}:{composition_id:localId(),composition_name:`${item.composition_name} 副本`,access_level:'private',is_pinned:false,lifecycle_status:'active',metadata_revision:1,created_at:stamp,updated_at:stamp,current_version_no:1,versions:[version],migration_source_key:null};rows.push(copy);await saveLocalRows(rows);return}await getJSON('ghgy-local:showcase-compositions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({composition_name:`${item.composition_name} 副本`,access_level:'private',is_pinned:false,layout:detail.layout,items:detail.items})})}
function bindCard(card,item){
  card.querySelector('[data-access-tag]')?.addEventListener('click',()=>openAccessDialog(item,'toggle'));card.querySelector('[data-publish-tag]')?.addEventListener('click',()=>openAccessDialog(item,'blocked'));
  card.querySelector('[data-open]')?.addEventListener('click',()=>openComposition(item));card.querySelector('[data-compose]')?.addEventListener('click',()=>openCompositionForComposer(item));card.querySelector('[data-move]')?.addEventListener('click',async()=>{const folders=(ui.library.folders||[]).filter(folder=>folder.lifecycle_status!=='trashed'),choices=['0. 未归档',...folders.map((folder,index)=>`${index+1}. ${folder.folder_name}`)],answer=prompt(`移动到哪个文件夹？\n${choices.join('\n')}`,String(Math.max(0,folders.findIndex(folder=>folder.folder_id===item.folder_id)+1)));if(answer==null)return;const index=Number(answer);if(!Number.isInteger(index)||index<0||index>folders.length)return setStatus('文件夹编号无效。',true);try{await metadata(item,{folder_id:index?folders[index-1].folder_id:null});ui.selectedFolder=index?folders[index-1].folder_id:'';loadLibrary()}catch(error){setStatus(error.message,true)}});card.querySelector('[data-pin]')?.addEventListener('click',async()=>{try{await metadata(item,{is_pinned:!item.is_pinned});loadLibrary()}catch(error){setStatus(error.message,true)}});card.querySelector('[data-rename]')?.addEventListener('click',async()=>{const name=prompt('组合新名称',item.composition_name);if(!name?.trim()||name.trim()===item.composition_name)return;try{await metadata(item,{composition_name:name.trim()});loadLibrary()}catch(error){setStatus(error.message,true)}});card.querySelector('[data-copy]')?.addEventListener('click',async()=>{try{await copyComposition(item);loadLibrary()}catch(error){setStatus(error.message,true)}});card.querySelector('[data-trash]')?.addEventListener('click',async()=>{try{await lifecycle(item,'trashed');loadLibrary()}catch(error){setStatus(error.message,true)}});card.querySelector('[data-restore]')?.addEventListener('click',async()=>{try{await lifecycle(item,'active');loadLibrary()}catch(error){setStatus(error.message,true)}});card.querySelector('[data-delete]')?.addEventListener('click',async()=>{try{await permanentDelete(item);loadLibrary()}catch(error){setStatus(error.message,true)}})
}
async function createFolder(){const name=prompt('新文件夹名称');if(!name?.trim())return;try{if(localMode()){const rows=localFolders(),stamp=now(),folder={folder_id:localId().replace(/^BLC/,'BLF'),folder_name:name.trim(),sort_order:rows.length,is_pinned:false,pin_rank:null,access_level:'browser_local',lifecycle_status:'active',trashed_at:null,metadata_revision:1,created_at:stamp,updated_at:stamp};rows.push(folder);await saveLocalFolders(rows);ui.selectedFolder=folder.folder_id}else{const result=await getJSON('ghgy-local:showcase-folders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({folder_name:name.trim(),access_level:'private',sort_order:(ui.library.folders||[]).length})});ui.selectedFolder=result.folder.folder_id}await loadLibrary();setStatus(`文件夹“${name.trim()}”已创建。`)}catch(error){setStatus(error.message,true)}}
async function migrateLegacyDraft(){
  if(localMode()&&window.GHGY_WORKSPACE_READY)await window.GHGY_WORKSPACE_READY;
  if(!state.charts?.length)return;const draft=safeJSON(localValue(DRAFT_KEY)||'null',null),ids=safeJSON(localValue(ORDER_KEY)||'[]',[]).filter(id=>state.showcase.has(id));if(!draft||!ids.length)return;
  if(localMode()){if(localRows().some(row=>row.migration_source_key===MIGRATION_KEY))return;composer().loadDraft(draft);const detail=await saveComposition('未命名组合（迁移）','private',false,{saveAs:true,migration:true});setStatus(`临时草稿已无损迁移为“${detail.composition_name}”。`);return}
  composer().loadDraft(draft);const detail=await saveComposition('未命名组合（迁移）','private',false,{saveAs:true,migration:true});setStatus(detail.migrated_existing?'迁移组合已存在，未重复创建。':'临时草稿已无损迁移为“未命名组合（迁移）”。')
}
function newComposition(){composer().runtime.currentComposition=null;composer().runtime.boundCharts.clear();composer().runtime.boundAssets.clear();composer().runtime.boundItems.clear();updateCurrentUI();switchView('showcase');switchMode('compose')}
function upgradeAll(){for(const[key,item]of[...composer().runtime.boundItems])if(item.asset_type!=='tb'&&!item.tb_page_id){composer().runtime.boundItems.delete(key);composer().runtime.boundAssets.delete(key);composer().runtime.boundCharts.delete(key)}byId('composerUpgradeAll').hidden=true;byId('composerVersionStatus').textContent='已选择升级有新版的研究图；保存后才写入新绑定。TB 页继续精确绑定原版本，未自动替换。';composer().renderOrderList();composer().refreshPreview().catch(error=>setStatus(error.message,true))}
function releaseBinding(key){composer().runtime.boundItems.delete(key);composer().runtime.boundAssets.delete(key);composer().runtime.boundCharts.delete(key);updateCurrentUI()}
function releaseAllBindings(){composer().runtime.boundItems.clear();composer().runtime.boundAssets.clear();composer().runtime.boundCharts.clear();updateCurrentUI()}
function init(){
  if(!byId('showcaseLibraryTab')||!composer())return;byId('showcaseLibraryTab').onclick=()=>switchMode('library');byId('showcaseBrowseTab').addEventListener('click',()=>switchMode('browse'));byId('showcaseComposeTab').addEventListener('click',()=>switchMode('compose'));byId('composerOpenLibrary').onclick=()=>switchMode('library');byId('showcaseLibraryActive').onclick=()=>{ui.trash=false;renderLibrary()};byId('showcaseLibraryTrash').onclick=()=>{ui.trash=true;renderLibrary()};byId('showcaseLibrarySearch').oninput=event=>{ui.libraryQuery=event.currentTarget.value;renderLibrary()};byId('showcaseLibrarySearchClear').onclick=()=>{ui.libraryQuery='';byId('showcaseLibrarySearch').value='';renderLibrary();byId('showcaseLibrarySearch').focus()};byId('showcaseNewFolder').onclick=createFolder;byId('showcaseNewComposition').onclick=newComposition;byId('compositionResearchBack').onclick=()=>{ui.previewRun+=1;switchView('compositionLibrary');showLibrary()};byId('compositionResearchRefresh').onclick=refreshResearch;byId('compositionResearchActivateAll').onclick=activateAllResearch;byId('compositionResearchExport').onclick=()=>openCompositionForComposer();byId('compositionResearchAll').onclick=()=>{ui.researchFilter='all';renderResearch()};byId('compositionResearchNewer').onclick=()=>{ui.researchFilter='newer';renderResearch()};byId('compositionResearchCopySourceNote').onclick=()=>{const source=byId('compositionResearchSourceNote').textContent;if(source&&source!=='尚未填写原始说明。')byId('compositionResearchItemNote').value=source};byId('compositionResearchTextSave').onclick=saveResearchText;byId('composerSaveComposition').onclick=()=>openSaveDialog(false);byId('composerSaveAsComposition').onclick=()=>openSaveDialog(true);byId('composerUpgradeAll').onclick=upgradeAll;document.querySelectorAll('input[name="compositionAccess"]').forEach(input=>input.onchange=togglePublicConfirm);byId('compositionSaveConfirm').onclick=confirmSave;document.querySelectorAll('input[name="compositionQuickAccess"]').forEach(input=>input.onchange=changeQuickAccessTarget);byId('compositionAccessConfirmFirst').onchange=updateAccessDialog;byId('compositionAccessConfirmSecond').onchange=updateAccessDialog;byId('compositionAccessApply').onclick=applyAccessChange;updateCurrentUI();let attempts=0,timer=setInterval(()=>{attempts+=1;if(state.charts?.length){clearInterval(timer);migrateLegacyDraft().catch(error=>setStatus(`临时草稿迁移未完成：${error.message}`,true))}else if(attempts>40)clearInterval(timer)},250)
}
init();
window.releaseCompositionAssetBinding=releaseBinding;
window.releaseAllCompositionAssetBindings=releaseAllBindings;
window.CompositionLibrary={showLibrary,restoreResearchView,openComposition,openCompositionForComposer};
})();
